version: '3.9'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: big_online
      MYSQL_USER: tuanlee
      MYSQL_PASSWORD: tuanlee
    volumes:
      - ./data/mysql:/var/lib/mysql
